* xmpp-repl
** Purpose
xmpp-repl provides a REPL that one may use to communicate with a Common Lisp image over XMPP using any XMPP client.
** Description
xmpp-repl provides Gray streams which allow one to send data to and from an XMPP account transparently.
It also provides a simple yet fully featured REPL using these stream classes.

** Usage
xmpp-repl requires an XMPP account to be already set up in addition to any that will be communicated with.
In order to establish a REPL with ~recipient@hostname.com~:

#+BEGIN_SRC lisp
  (xmpp-repl:connect-and-auth "host" "username" "password")
  (xmpp-repl:xmpp-repl "recipient@hostname.com")
#+END_SRC


** Installation
Easiest when quicklisp is installed. Clone to quicklisp/local-projects and run
#+BEGIN_SRC lisp
(ql:quickload :xmpp-repl)
#+END_SRC

** Improvements and open questions
+ How to deal with multiplexing? Several Lisp images (potentially on different machines) communicating with the same account
+ How to deal with all the I/O customization variables? Perhaps bind all of them to a bidirectional XMPP stream.

** Author

+ Selwyn Simsek

** Licence
BSD-2

** Copyright

Copyright (c) 2024 Selwyn Simsek
